version: '3.8'

services:
    
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
        ports:
            - "5432:5432"
    rabbitmq:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672"
            - "15672:15672"
    seq:
        image: datalust/seq
        environment:
            ACCEPT_EULA: Y
        ports:
            - "5341:5341"
            - "80:80"
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "8080:8080"
        command: start-dev