apiVersion: v1
kind: Namespace
metadata:
  name: hotelup-customer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelup-customer-deployment
  labels:
    app: hotelup-customer
  namespace: hotelup-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotelup-customer
  template:
    metadata:
      name: hotelup-customer
      labels:
        app: hotelup-customer
    spec:
      containers:
        - name: hotelup-customer
          image: wiaz/hotelup.customer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hotelup-customer-service
  labels:
    app: hotelup-customer
  namespace: hotelup-customer
spec:
    selector:
        app: hotelup-customer
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
    type: LoadBalancer
      